services:
  laravelapp:
    container_name: laravelapp
    build:
      context: dockerfiles
      dockerfile: laravel.Dockerfile
    volumes:
      - './src:/var/www/chat'
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './src:/var/www/chat'
    depends_on:
      - db
      - php
      - composer
      - artisan
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - './src:/var/www/chat'
  db:
    container_name: postgres_laravel
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    volumes:
      - './db_data:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
#  mysql:
#    image: mysql:8.0
#    ports:
#      - "3316:3306"
#    env_file:
#      - env/mysql.env
#    volumes:
#      - db_data:/var/lib/mysql
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - './src:/var/www/chat'
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - './src:/var/www/chat'
    entrypoint:
      - php
      - /var/www/chat/artisan
  npm:
    image: node:20
    working_dir: /var/www/chat
    entrypoint: ["npm"]
    volumes:
      - './src:/var/www/chat'
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379

volumes:
  db_data: null
