version: '3.8'
services:
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './src:/var/www/project'
    depends_on:
      - db
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - './src:/var/www/project'
  db:
    container_name: postgres_laravel
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
    volumes:
      - './db_data:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
#  mysql:
#    image: mysql:8.0
#    ports:
#      - "3316:3306"
#    env_file:
#      - env/mysql.env
#    volumes:
#      - db_data:/var/lib/mysql
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - './src:/var/www/project'
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - './src:/var/www/project'
    entrypoint:
      - php
      - /var/www/project/artisan
volumes:
  db_data: null
