version: "3.8"

services:
  nginx:
    image: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/pro-traffic-group
    depends_on:
      - db
      - php

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/pro-traffic-group

  db:
    container_name: postgres_laravel
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ptg
    volumes:
      - ./db_data:/var/lib/postgresql/data

  pgadmin:
     image: dpage/pgadmin4
     ports:
         - 5050:80
     environment:
         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
         - PGADMIN_DEFAULT_PASSWORD=password
     depends_on:
         - db

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/pro-traffic-group
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/pro-traffic-group
    entrypoint: [ "php", "/var/www/pro-traffic-group/artisan" ]

volumes:
  db_data:
